# Generated by Django 4.0 on 2022-03-20 09:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ups',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
