# Generated by Django 4.0 on 2022-03-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_ups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ups',
            new_name='upc',
        ),
    ]
