# Generated by Django 4.0 on 2022-03-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_ups_product_upc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='upc',
        ),
    ]
