# Generated by Django 4.0 on 2022-03-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_userbalancehistory_transactionsarchive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionsarchive',
            name='status',
        ),
    ]
