# Generated by Django 4.0 on 2022-03-24 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_username'),
        ('wallet', '0003_remove_transactionsarchive_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsarchive',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Charge'), (2, 'Purchase'), (3, 'Transfer')], default=1),
        ),
        migrations.AlterField(
            model_name='transactionsarchive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_archive', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='userbalancehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_transaction_archive', to='accounts.user'),
        ),
    ]
