# Generated by Django 4.0 on 2022-03-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_username'),
        ('wallet', '0004_transactionsarchive_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBalanceHistory',
            new_name='UserBalance',
        ),
    ]
