# Generated by Django 4.0 on 2022-03-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_username'),
        ('wallet', '0005_rename_userbalancehistory_userbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Charge'), (2, 'Purchase'), (3, 'Transfer_sent'), (4, 'Transfer_received')], default=1),
        ),
        migrations.AlterField(
            model_name='transactionsarchive',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Charge'), (2, 'Purchase'), (3, 'Transfer_sent'), (4, 'Transfer_received')], default=1),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='accounts.user')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sent', to='accounts.user')),
            ],
        ),
    ]
