# Generated by Django 4.0 on 2022-01-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount',
            new_name='discount_order',
        ),
    ]
