# Generated by Django 4.0 on 2022-01-20 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_discount_order_discount_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_order',
        ),
    ]
