# Generated by Django 4.0 on 2022-01-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_discount_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dis',
            field=models.IntegerField(default=None),
        ),
    ]
