# Generated by Django 4.0 on 2022-01-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_dis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dis',
        ),
    ]
