# Generated by Django 4.0 on 2022-01-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_discount_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='number',
            new_name='quantity',
        ),
    ]
